@host = http://localhost:5157

GET {{host}}/todos/
Accept: application/json

###

GET {{host}}/todos/1
Accept: application/json

###

// Okay
POST {{host}}/users/register
Content-Type: application/json
Accept: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xa@somewhere.com",
  "password": "Keep8Simple!"
}
###

// Created
POST {{host}}/users/registerCreated
Content-Type: application/json
Accept: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xa@somewhere.com",
  "password": "KeepItSimple1@"
}
###

// Bad request
POST {{host}}/users/register
Content-Type: application/json
Accept: application/json

{
  "firstName": "string",
  "lastName": "",
  "email": "xa.com",
  "password": "string"
}
###

// Bad Request password
POST {{host}}/users/register
Content-Type: application/json
Accept: application/json

{
  "firstName": "Xavier",
  "lastName": "John",
  "email": "xa@somewhere.com",
  "password": "KeepItSimple"
}
###

// Not found
GET {{host}}/users/notfound/213
Accept: application/json

###

// Conflict
GET {{host}}/users/conflict/213
Accept: application/json

###

// Forbidden
GET {{host}}/users/forbidden/213
Accept: application/json

###

// Unauthorized
GET {{host}}/users/unauthorized/213
Accept: application/json

###

// Unexpected
GET {{host}}/users/unexpected/213
Accept: application/json

###
### Automatic Validation - Invalid Email
# Email address is invalid (missing @) - returns 400 Bad Request
# The framework automatically validates EmailAddress during model binding
POST {{host}}/users/RegisterWithAutoValidation
Content-Type: application/json

{
    "firstName": "Xavier",
    "lastName": "John",
    "email": "not-an-email",
    "password": "SecurePass123!"
}

### Automatic Validation - Missing FirstName
# FirstName is null - returns 400 Bad Request
# RequiredString validation happens automatically
POST {{host}}/users/RegisterWithAutoValidation
Content-Type: application/json

{
    "lastName": "John",
    "email": "xavier@example.com",
    "password": "SecurePass123!"
}

### Automatic Validation - Empty LastName
# LastName is empty string - returns 400 Bad Request
POST {{host}}/users/RegisterWithAutoValidation
Content-Type: application/json

{
    "firstName": "Xavier",
    "lastName": "",
    "email": "xavier@example.com",
    "password": "SecurePass123!"
}

### Automatic Validation - Multiple Errors
# Multiple validation errors - all are collected and returned
# No firstName, invalid email format
POST {{host}}/users/RegisterWithAutoValidation
Content-Type: application/json

{
    "lastName": "John",
    "email": "invalid-email",
    "password": "SecurePass123!"
}
