namespace Trellis.Asp.ApiVersioning.Tests;

/// <summary>
/// Smoke test for <c>ApiVersionConstants</c>, generated by the bundled
/// <c>Trellis.Asp.ApiVersioning.SourceGenerator</c> from the
/// <c>&lt;TrellisApiVersion&gt;</c> MSBuild property declared in
/// <c>Trellis.Asp.ApiVersioning.Tests.csproj</c>. If the generator
/// is wired correctly, <see cref="ApiVersionConstants.Current"/> is
/// a compile-time literal — usable in <c>[ApiVersion(...)]</c> attribute
/// arguments — equal to the property value.
/// </summary>
public sealed class ApiVersionConstantsTests
{
    [Fact]
    public void Current_matches_TrellisApiVersion_MSBuild_property() =>
        // The test csproj declares <TrellisApiVersion>2026-11-12</TrellisApiVersion>.
        ApiVersionConstants.Current.Should().Be("2026-11-12");

    [Fact]
    public void CurrentNamespaceSuffix_is_namespace_safe() =>
        // 2026-11-12 -> v2026_11_12 (hyphens replaced with underscores; "v" prefix).
        ApiVersionConstants.CurrentNamespaceSuffix.Should().Be("v2026_11_12");

    [Fact]
    public void Current_is_const_and_usable_in_attribute_arguments()
    {
        // The const is compile-time visible, so this attribute compiles.
        var attr = typeof(VersionedSample).GetCustomAttributes(typeof(global::Asp.Versioning.ApiVersionAttribute), inherit: false);
        attr.Should().HaveCount(1);
    }

    [global::Asp.Versioning.ApiVersion(ApiVersionConstants.Current)]
    private sealed class VersionedSample;
}
