namespace Trellis.Asp.ApiVersioning.SourceGenerator;

using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Source generator that emits <c>ApiVersionConstants.g.cs</c> with compile-time C# constants
/// derived from the <c>&lt;TrellisApiVersion&gt;</c> MSBuild property. The generated constants
/// can be used in <c>[ApiVersion(...)]</c> attribute arguments, <c>CreatedAtRoute(...)</c> route
/// values, namespace suffixes, and tests — eliminating the literal-propagation drift across
/// controllers when the active API version changes.
/// </summary>
/// <remarks>
/// <para>
/// Wire the property in your <c>.csproj</c> or <c>Directory.Build.props</c>:
/// </para>
/// <code>
/// &lt;PropertyGroup&gt;
///   &lt;TrellisApiVersion&gt;2026-11-12&lt;/TrellisApiVersion&gt;
/// &lt;/PropertyGroup&gt;
/// </code>
/// <para>
/// The generator is bundled inside <c>Trellis.Asp.ApiVersioning.nupkg</c> under
/// <c>analyzers/dotnet/cs</c>, so consumers receive it transitively.
/// </para>
/// <para>
/// Generated output:
/// </para>
/// <code>
/// namespace Trellis.Asp.ApiVersioning;
///
/// public static class ApiVersionConstants
/// {
///     public const string Current = "2026-11-12";
///     public const string CurrentNamespaceSuffix = "v2026_11_12";
/// }
/// </code>
/// <para>
/// When <c>TrellisApiVersion</c> is unset, the generator emits no source. Consumers can then
/// continue to hard-code version strings or opt into the convention later.
/// </para>
/// </remarks>
[Generator]
public sealed class ApiVersionConstantsGenerator : IIncrementalGenerator
{
    private const string PropertyName = "TrellisApiVersion";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var versionProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property." + PropertyName, out var version);
                return string.IsNullOrWhiteSpace(version) ? null : version;
            });

        context.RegisterSourceOutput(versionProvider, static (ctx, version) =>
        {
            if (version is null) return;

            var namespaceSuffix = "v" + SanitiseForIdentifier(version);
            var source = BuildSource(version, namespaceSuffix);
            ctx.AddSource("ApiVersionConstants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string SanitiseForIdentifier(string version)
    {
        // Replace anything that isn't a valid C# identifier character with '_'.
        // Common shapes: "2026-11-12" → "2026_11_12", "1.0" → "1_0", "2026-11-12-preview" → "2026_11_12_preview".
        var sb = new StringBuilder(version.Length);
        foreach (var ch in version)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                sb.Append(ch);
            else
                sb.Append('_');
        }

        return sb.ToString();
    }

    private static string BuildSource(string version, string namespaceSuffix)
    {
        // Note: const-string concat at compile time means consumers can use
        // `ApiVersionConstants.Current` in `[ApiVersion(...)]` attribute arguments.
        const string nl = "\r\n";
        return
            "// <auto-generated/>" + nl +
            "#nullable enable" + nl +
            nl +
            "namespace Trellis.Asp.ApiVersioning;" + nl +
            nl +
            "/// <summary>" + nl +
            "/// Compile-time constants for the current API version, generated from the" + nl +
            "/// <c>TrellisApiVersion</c> MSBuild property by Trellis.Asp.ApiVersioning.SourceGenerator." + nl +
            "/// </summary>" + nl +
            "public static class ApiVersionConstants" + nl +
            "{" + nl +
            "    /// <summary>The active API version literal (e.g. \"2026-11-12\").</summary>" + nl +
            "    public const string Current = \"" + EscapeForString(version) + "\";" + nl +
            nl +
            "    /// <summary>" + nl +
            "    /// The namespace-safe suffix for the active version (e.g. \"v2026_11_12\")," + nl +
            "    /// suitable for namespace folders and class-name suffixes." + nl +
            "    /// </summary>" + nl +
            "    public const string CurrentNamespaceSuffix = \"" + EscapeForString(namespaceSuffix) + "\";" + nl +
            "}" + nl;
    }

    private static string EscapeForString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
