// Cookbook Recipe 1 — CRUD aggregate (DDD value objects + entity + repository contract).
namespace CookbookSnippets.Recipe01;

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Trellis;
using Trellis.Authorization;

// Strongly-typed ID: source-generated factory, equality, parsing, JSON converter.
public sealed partial class OrderId : RequiredGuid<OrderId>;

// Value object backed by a 3-letter ISO 4217 currency code.
[StringLength(3, MinimumLength = 3)]
public sealed partial class CurrencyCode : RequiredString<CurrencyCode>;

// Composite value object via primary-constructor class.
public sealed class Money(decimal amount, CurrencyCode currency) : ValueObject
{
    public decimal Amount { get; } = amount;
    public CurrencyCode Currency { get; } = currency;

    protected override IEnumerable<System.IComparable?> GetEqualityComponents()
    {
        yield return Amount;
        yield return Currency;
    }
}

// Trellis convention: model finite domain states as RequiredEnum<TSelf>
// (NOT C# enums). The partial keyword triggers the source generator.
public partial class OrderStatus : RequiredEnum<OrderStatus>
{
    public static readonly OrderStatus Draft = new();
    public static readonly OrderStatus Submitted = new();
    public static readonly OrderStatus Cancelled = new();
}

// Aggregate root.
public sealed class Order : Aggregate<OrderId>
{
    public Money Total { get; private set; } = default!;
    public OrderStatus Status { get; private set; } = OrderStatus.Draft;

    // Owner identifier referenced by Recipe 7's resource-based authorization sample.
    // Typed as Trellis.Authorization.ActorId so the auth check stays type-safe end-to-end
    // (rather than dropping to string and relying on implicit conversions).
    public ActorId OwnerId { get; private set; } = default!;

    private Order(OrderId id) : base(id) { }   // EF Core ctor

    public static Result<Order> Create(OrderId id, Money total) =>
        Result.Ok(new Order(id) { Total = total, Status = OrderStatus.Draft });

    // Exercises the protected `DomainEvents` member inherited from Aggregate<TId>.
    // Compile-verifies the cookbook's Recipe 1 inherited-members callout claim
    // that subclasses can `DomainEvents.Add(...)` without redeclaring the property.
    public Result<Order> Submit()
    {
        DomainEvents.Add(new OrderSubmittedEvent(Id));
        Status = OrderStatus.Submitted;
        return Result.Ok(this);
    }
}

// Domain event used by Order.Submit() to compile-check the inherited DomainEvents surface.
public sealed record OrderSubmittedEvent(OrderId OrderId) : IDomainEvent
{
    public DateTimeOffset OccurredAt { get; } = DateTimeOffset.UtcNow;
}

// Repository contract — uses Maybe<T> for "may legitimately find nothing"
// Reserve Result<T> for failures the caller can act on.
public interface IOrderRepository
{
    Task<Maybe<Order>> FindAsync(OrderId id, CancellationToken ct);
    void Add(Order order);
}

// ---------------------------------------------------------------------------
// Compile-checked demonstrator of the inherited surface enumerated in Recipe 1.
//
// The cookbook's Recipe 1 "What it shows" callout enumerates the members
// `RequiredGuid<T>`, `RequiredString<T>`, `ValueObject`, and `Aggregate<TId>`
// give a derived type. The methods below invoke each claimed API so that CI
// compile-checks the cookbook prose against the real Trellis source. If a
// signature changes or a method disappears, this file fails to build and the
// cookbook callout must be updated to match.
//
// These methods are not invoked at runtime; they exist purely as a contract
// pin guarding against drift between the cookbook prose and the framework
// public surface.
// ---------------------------------------------------------------------------
internal static class Recipe1InheritedSurface
{
    public static void RequiredGuid_GeneratedSurface(Guid g, Guid? gn, string? s, IFormatProvider? fp)
    {
        // TryCreate overloads source-generated by RequiredPartialClassGenerator.
        Result<OrderId> r1 = OrderId.TryCreate(g);
        Result<OrderId> r2 = OrderId.TryCreate(g, "fieldName");
        Result<OrderId> r3 = OrderId.TryCreate(gn, "fieldName");
        Result<OrderId> r4 = OrderId.TryCreate(s, "fieldName");

        // Factory helpers specific to RequiredGuid.
        OrderId v4 = OrderId.NewUniqueV4();
        OrderId v7 = OrderId.NewUniqueV7();

        // IParsable<TSelf>.
        OrderId parsed = OrderId.Parse(Guid.NewGuid().ToString(), fp);
        bool tryParsed = OrderId.TryParse(Guid.NewGuid().ToString(), fp, out OrderId? roundTrip);

        // Explicit operator from underlying primitive.
        OrderId cast = (OrderId)g;

        // Inherited value access + equality.
        Guid value = parsed.Value;
        int hash = parsed.GetHashCode();
        bool eq = parsed.Equals(v4);

        _ = (r1, r2, r3, r4, v7, value, hash, eq, tryParsed, roundTrip, cast);
    }

    public static void RequiredString_GeneratedSurface(string? s, IFormatProvider? fp)
    {
        // RequiredString emits only the nullable-arg form.
        Result<CurrencyCode> r = CurrencyCode.TryCreate(s, "fieldName");

        CurrencyCode parsed = CurrencyCode.Parse("USD", fp);
        bool tryParsed = CurrencyCode.TryParse("USD", fp, out CurrencyCode? roundTrip);
        CurrencyCode cast = (CurrencyCode)"USD";

        // Inherited Value plus the string pass-throughs.
        string value = parsed.Value;
        int len = parsed.Length;
        bool starts = parsed.StartsWith("U");
        bool contains = parsed.Contains("S");
        bool ends = parsed.EndsWith("D");

        _ = (r, value, len, starts, contains, ends, tryParsed, roundTrip, cast);
    }

    public static void ValueObject_InheritedSurface(Money a, Money b)
    {
        // Equality + comparison + hashing all derived from GetEqualityComponents.
        bool eq = a == b;
        bool ne = a != b;
        bool lt = a < b;
        bool le = a <= b;
        bool gt = a > b;
        bool ge = a >= b;
        bool eqMethod = a.Equals(b);
        bool eqObj = a.Equals((object)b);
        int hash = a.GetHashCode();
        int cmp = a.CompareTo(b);

        _ = (eq, ne, lt, le, gt, ge, eqMethod, eqObj, hash, cmp);
    }

    public static void Aggregate_InheritedSurface(Order o)
    {
        // Identity + persistence-managed ETag + change tracking via inherited members.
        OrderId id = o.Id;
        string etag = o.ETag;
        bool changed = o.IsChanged;

        // Public IAggregate surface for uncommitted domain events.
        IReadOnlyList<IDomainEvent> events = ((IAggregate)o).UncommittedEvents();

        _ = (id, etag, changed, events);
    }
}